web: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
worker: python -m celery -A config worker --loglevel=info --concurrency=2
beat: python -m celery -A config beat --loglevel=info
